# Generated by Django 4.1.5 on 2023-01-10 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_categorymodel_parent_alter_unitmodel_base"),
    ]

    operations = [
        migrations.AddField(
            model_name="unitmodel",
            name="conversion_rate",
            field=models.FloatField(default=1.0),
        ),
    ]
